In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
import warnings
import os

warnings.filterwarnings('ignore')
pd.options.display.float_format = '{:.4f}'.format

import netwulf as nw
import networkx as nx

### With Endometriosis Graph (Dairy)

In [2]:
# column names, for future use
# filter1 = ['powderedmilk', 'RTDmilk', 'cheese', 'cream', 'leche', 'milo', 'ovaltine',
#            'cocoa', 'sustagen', 'enervon', 'coffee3in1', 'tea', 'butter', 'margarine',
#            'cake', 'biscuit', ]

# note that input excel has already been cleaned prior to below run. cleanup done as follows:
# *removed links with no dairy item for any connected nodes
# *filtered values <0.2 and >-0.1, based on earlier paper
df_with_endo = pd.read_excel('with_endometriosis_habits_withdairy_2.xls')
df_with_endo.columns = ['food1', 'food2', 'weight']

# this line sets absolute value for corrs; can uncomment just in case error due to nega value arises
# df_with_endo[df_with_endo.columns[df_with_endo.dtypes != np.object]] = df_with_endo[df_with_endo.columns[df_with_endo.dtypes != np.object]].abs()

df_with_endo.head()

            food1    food2  weight
0          pancit  oatmeal  0.2900
1  instantnoodles  oatmeal  0.2900
2            Spag  oatmeal -0.1200
3            cake    pizza  0.4300
4         cookies  pancake  0.2800

In [3]:
# this lists dairy items; this list tags dairy items as '1', else '0'
df_dairy = pd.read_excel('dairy_or_not.xlsx')
# df_dairy.head()
df_dairy

               food  group
0        arrozcaldo      0
1            pancit      0
2    instantnoodles      0
3          ricecake      0
4         tortillas      0
..              ...    ...
103         porkfat      0
104      brown_rice      0
105       condensed      1
106           cocoa      1
107      cookingoil      0

[108 rows x 2 columns]

In [ ]:
# list of dairy items search terms:
# milk
# milo
# ovaltine
# yoghurt/yogurt
# sustagen
# enervon
# cheese
# ice cream
# creamer
# butter
# chocolate
# chocopowder
# halo halo
# oatmeal
# pandesal
# bread
# monay
# pizza
# cake
# biscuit
# bake
# tablea
# tea
# margarine
# cocoa
# lecheflan
# cookies
# coffee3in1
# condensed

In [4]:
bb = df_dairy.set_index('food')['group'].to_dict()
#bb

In [5]:
# step matches dairy items list with the input correlation file
G = nx.from_pandas_edgelist(df_with_endo, 'food1', 'food2', edge_attr='weight')
nx.set_node_attributes(G, bb, 'group')

In [6]:
# visualizing step
nw.visualize(G)

(None, None)

In [7]:
# uncomment to display correlation value in edges
# edge_labels=dict([((u,v,),d['weight'])
#              for u,v,d in G.edges(data=True)])

# for u,v in edge_labels.items():
#     nw.add_edge_label(ax,stylized_network,u,label=v)

# stylized_network, default_config = nw.visualize(G)

# fig, ax = nw.draw_netwulf(stylized_network)
# plt.figure(figsize=(20,20))
# nw.draw_netwulf(stylized_network,fig,ax)

### WIthout Endometriosis

In [8]:
df_without_endo = pd.read_excel('without_endometriosis_habits_withdairy_2.xls')
df_without_endo.columns = ['food1', 'food2', 'weight']
df_without_endo.head()

     food1       food2  weight
0   pancit     oatmeal  0.2600
1    pizza  fried_rice  0.2400
2    pizza      burger  0.4000
3  pancake        cake  0.2800
4  biscuit     cookies  0.2200

In [9]:
H = nx.from_pandas_edgelist(df_without_endo, 'food1', 'food2', edge_attr='weight')
nx.set_node_attributes(H, bb, 'group')

In [10]:
nw.visualize(H)

(None, None)